#!/usr/bin/env bash
set -euo pipefail

# aws cli
curl -f "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip -o awscliv2.zip
sudo ./aws/install --update

rm -rf awscliv2.zip aws/

# eksctl 
ARCH=amd64
PLATFORM="$(uname -s)_$ARCH"

curl -fsLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
curl -fsL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep "$PLATFORM" | sha256sum --check

tar -xzf "eksctl_$PLATFORM.tar.gz" -C /tmp && rm "eksctl_$PLATFORM.tar.gz"

sudo install -m 0755 /tmp/eksctl /usr/local/bin && rm /tmp/eksctl

