#!/usr/bin/env bash

VERSION=1.25.5

wget https://go.dev/dl/go$VERSION.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go$VERSION.linux-amd64.tar.gz

rm go$VERSION.linux-amd64.tar.gz

echo -e "\nPATH=\"\$PATH:/usr/local/go/bin\"" >> ~/.bashrc

export PATH=$PATH:/usr/local/go/bin

# Install debugger
go install github.com/go-delve/delve/cmd/dlv@latest
