#!/usr/bin/env bash

wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz

rm go1.24.1.linux-amd64.tar.gz

echo -e "\nPATH=\$PATH:/usr/local/go/bin" >> ~/.bashrc
