#!/usr/bin/env bash

API_URL="https://api.github.com/repos/neovim/neovim/releases/latest"
LATEST_VERSION=$(curl -s $API_URL | jq -r '.tag_name')
OUTPUT_DIR=$HOME/code/neovim

if [[ -d $OUTPUT_DIR ]]; then
    rm -rf $OUTPUT_DIR
fi

git clone -b $LATEST_VERSION https://github.com/neovim/neovim.git $OUTPUT_DIR
sudo apt install cmake gettext lua5.1 liblua5.1-0-dev

cd $OUTPUT_DIR
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
