#!/usr/bin/env bash

# TODO: Get latest version from repo (curl endpoint for releases, get latest)
VERSION=v0.11.5
OUTPUT_DIR=$HOME/projects/neovim

if [[ -d $OUTPUT_DIR ]]; then
    rm -rf $OUTPUT_DIR
fi

git clone -b $VERSION https://github.com/neovim/neovim.git $HOME/projects/neovim
sudo apt install cmake gettext lua5.1 liblua5.1-0-dev

cd $OUTPUT_DIR
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
