#!/usr/bin/env bash

FILENAME="obisidan.deb"

wget -O $FILENAME https://github.com/obsidianmd/obsidian-releases/releases/download/v1.10.6/obsidian_1.10.6_amd64.deb

sudo apt install ./$FILENAME

rm $FILENAME

sudo apt install ./$FILENAME

rm $FILENAME
